* A PubSub Protocol and its Simulator

This is a pubsub protocol, dubbed ~gossipsub~, aka ~meshsub/1.0.0~.
The basic idea is to start from a connected network with an arbitrary
degree and reduce it to a mesh with a specific degree. Messages are
forwarded through the reduced mesh. The mesh is augmented by /gossip/
about forwarded messages, which is regularly forwarded to a random subset
of known peers with a heartbeat.

* Installation

The code is written in Gerbil, and you can install it through the
Gerbil package manager:

#+BEGIN_EXAMPLE
$ gxpkg install github.com/vyzo/gerbil-simsub
#+END_EXAMPLE

* Simulation

The simulator constructs a network of ~N~ nodes, and randomly connects
it with a connectivity degree ~N-connect~.
There is a random latency between any pair of nodes, selected uniformly
in the ~[.01s, .15s]~ interval.
The simulatoion script sends a number ~M~ of messages, by selecting ~fanout~ random
peers and publishing to them. Each successive message is sent after some delay
~M-delay~.

#+BEGIN_EXAMPLE
$ gxi
> (import :vyzo/simsub/scripts)
> (simple-gossipsub-simulation trace: void) ; N = 100, N-connect = 10, M = 10, M-delay = 1
=== simulation summary ===
nodes: 100
messages: 10
fanout: 5
publish: 50
deliver: 1000
!!gossipsub.link: 378
!!gossipsub.iwant: 16
!!pubsub.publish: 6546
!!gossipsub.prune: 47
!!gossipsub.ihave: 7230
!!gossipsub.graft: 724
!!gossipsub.unlink: 47
!!pubsub.connect: 1000

> (simple-gossipsub-simulation trace: void messages: 100 message-delay: .1)
=== simulation summary ===
nodes: 100
messages: 100
fanout: 5
publish: 500
deliver: 10000
!!gossipsub.link: 380
!!gossipsub.prune: 71
!!pubsub.publish: 64306
!!gossipsub.ihave: 7806
!!gossipsub.unlink: 71
!!gossipsub.graft: 748
!!gossipsub.iwant: 179
!!pubsub.connect: 1000

> (simple-gossipsub-simulation trace: void messages: 1000 message-delay: .01)
=== simulation summary ===
nodes: 100
messages: 1000
fanout: 5
publish: 5000
deliver: 100000
!!gossipsub.link: 365
!!gossipsub.iwant: 1288
!!pubsub.publish: 668626
!!gossipsub.prune: 50
!!gossipsub.ihave: 14436
!!gossipsub.graft: 752
!!gossipsub.unlink: 50
!!pubsub.connect: 1000

#+END_EXAMPLE

If you want to see a trace of the developing simulation,
then omit the ~trace: void~ argument to the simulation invocation.
The default ~trace:~ will be ~displayln~, which will print out the simulation
in the current output port.
